Repository jhipster/generator-jhipster-micronaut, pull requests merged in 2020-10, with the labels that each got.

#183 Upgrade micronaut-data to 2.0.0 and micronaut-core to 2.1.0
  generators/constants.js
Labels: dependencies

#185 feat: build and run from Docker Support
  README.md
  docker/Dockerfile
Labels: documentation 📝, hacktoberfest-accepted

#187 update micronaut to 2.1.1
  generators/constants.js
Labels: dependencies, hacktoberfest-accepted

#188 Microservice support
  .github/workflows/samples.yml
  generators/app/prompts.js
  generators/constants.js
  generators/server/files.js
  generators/server/index.js
  generators/server/prompts.js
  generators/server/templates/build.gradle.ejs
  generators/server/templates/gradle.properties.ejs
  generators/server/templates/openapi.properties.ejs
  generators/server/templates/pom.xml.ejs
  generators/server/templates/src/main/docker/app.yml.ejs
  generators/server/templates/src/main/docker/config/consul-config/application.yml.ejs
  generators/server/templates/src/main/docker/consul.yml.ejs
  generators/server/templates/src/main/java/package/App.java.ejs
  generators/server/templates/src/main/java/package/web/rest/SwaggerResource.java.ejs
  generators/server/templates/src/main/resources/application-dev.yml.ejs
  generators/server/templates/src/main/resources/application-prod.yml.ejs
  generators/server/templates/src/main/resources/application.yml.ejs
  generators/server/templates/src/main/resources/bootstrap.yml.ejs
  generators/server/templates/src/test/java/package/config/CorsTest.java.ejs
  generators/server/templates/src/test/java/package/service/UserServiceIT.java.ejs
  generators/server/templates/src/test/resources/application-test.yml.ejs
  generators/server/templates/src/test/resources/bootstrap-test.yml.ejs
  test-integration/samples/gradle-ms-eureka-oauth.jdl
  test-integration/samples/mvn-ms-consul-jwt.jdl
  test-integration/scripts/03-dep-containers.sh
  test-integration/scripts/04-server-tests.sh
Labels: enhancement 💎, hacktoberfest-accepted

#194 Use micronaut-cache-caffeine when cacheProvider is caffeine
  generators/server/templates/pom.xml.ejs
Labels: dependencies, hacktoberfest-accepted

#195 update main generator to 6.10.4
  package-lock.json
  package.json
  test-integration/samples/fixes/gradle-jwt-react/package.json
Labels: dependencies, hacktoberfest-accepted

#200 update micronaut data
  generators/constants.js
Labels: dependencies, hacktoberfest-accepted
