Repository jhipster/generator-jhipster-micronaut, pull requests merged in 2020-06, with the labels that each got.

#93 provide caffeine cache implementation
  README.md
  generators/constants.js
  generators/server/prompts.js
  generators/server/templates/gradle.properties.ejs
  generators/server/templates/pom.xml.ejs
  generators/server/templates/src/main/java/package/config/CacheConfiguration.java.ejs
  generators/server/templates/src/main/java/package/util/JHipsterProperties.java.ejs
Labels: enhancement 💎

#101 Use jsr330 componentModel in EntityMapper
  generators/entity-server/templates/src/main/java/package/service/mapper/EntityMapper.java.ejs
Labels: bug 🐞

#102 Use javax @Transaction and micronaut @ReadOnly on service methods
  generators/common/templates/README.md.ejs
  generators/entity-server/templates/src/main/java/package/common/get_filtered_template.ejs
  generators/entity-server/templates/src/main/java/package/service/EntityQueryService.java.ejs
  generators/entity-server/templates/src/main/java/package/service/EntityService.java.ejs
  generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs
  generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
Labels: bug 🐞

#110 Fixes assertions in JWTFilterTest and disables Basic Auth
  generators/server/templates/src/main/resources/application.yml.ejs
  generators/server/templates/src/test/java/package/security/jwt/JWTFilterTest.java.ejs
Labels: bug 🐞

#112 Use micronaut family member in generated app
  generators/client/files.js
  generators/client/templates/angular/home/home.scss.ejs
  generators/client/templates/angular/src/main/webapp/content/images/jhipster_family_member_4.svg
  generators/client/templates/angular/src/main/webapp/content/images/jhipster_family_member_4_head-192.png
  generators/client/templates/angular/src/main/webapp/content/images/jhipster_family_member_4_head-256.png
  generators/client/templates/angular/src/main/webapp/content/images/jhipster_family_member_4_head-384.png
  generators/client/templates/angular/src/main/webapp/content/images/jhipster_family_member_4_head-512.png
  generators/client/templates/angular/src/main/webapp/manifest.webapp.ejs
  generators/client/templates/react/home/home.scss.ejs
  generators/client/templates/react/src/main/webapp/content/images/jhipster_family_member_4.svg
  generators/client/templates/react/src/main/webapp/content/images/jhipster_family_member_4_head-192.png
  generators/client/templates/react/src/main/webapp/content/images/jhipster_family_member_4_head-256.png
  generators/client/templates/react/src/main/webapp/content/images/jhipster_family_member_4_head-384.png
  generators/client/templates/react/src/main/webapp/content/images/jhipster_family_member_4_head-512.png
  generators/client/templates/react/src/main/webapp/manifest.webapp.ejs
Labels: enhancement 💎

#108 update to micronaut 2.0.0
  .github/workflows/samples.yml
  generators/constants.js
  generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs
  generators/server/files.js
  generators/server/templates/build.gradle.ejs
  generators/server/templates/gradle.properties.ejs
  generators/server/templates/gradle/profile_dev.gradle.ejs
  generators/server/templates/pom.xml.ejs
  generators/server/templates/src/main/java/package/security/BcryptPasswordEncoder.java.ejs
  generators/server/templates/src/main/java/package/security/DatabaseAuthenticationProvider.java.ejs
  generators/server/templates/src/main/java/package/security/JHipsterOpenIdUserDetailsMapper.java.ejs
  generators/server/templates/src/main/java/package/security/PasswordEncoder.java.ejs
  generators/server/templates/src/main/java/package/service/UserService.java.ejs
  generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
  generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
  generators/server/templates/src/main/java/package/web/rest/errors/handlers/ProblemRejectionHandler.java.ejs
  generators/server/templates/src/main/resources/application-dev.yml.ejs
  generators/server/templates/src/main/resources/application-prod.yml.ejs
  generators/server/templates/src/main/resources/application-test.yml.ejs
  generators/server/templates/src/main/resources/application.yml.ejs
  generators/server/templates/src/test/java/package/config/timezone/HibernateTimeZoneIT.java.ejs
  generators/server/templates/src/test/java/package/repository/timezone/DateTimeWrapper.java.ejs
  generators/server/templates/src/test/java/package/security/DomainUserDetailsServiceIT.java.ejs
  generators/server/templates/src/test/java/package/security/jwt/JWTFilterTest.java.ejs
  generators/server/templates/src/test/java/package/web/rest/AccountResourceIT.java.ejs
  generators/server/templates/src/test/java/package/web/rest/UserJWTControllerIT.java.ejs
  test-integration/samples/gradle-oauth-angular.jdl
  test-integration/samples/mvn-jwt-angular.jdl
  test-integration/scripts/04-server-tests.sh
  test-integration/scripts/06-build-app.sh
  test-integration/scripts/07-start-app.sh
Labels: dependencies
